// <auto-generated />
using System;
using BadmintonBookingAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BadmintonBookingAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310070522_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BadmintonBookingAPI.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TimeSlotId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BadmintonBookingAPI.Models.Court", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Courts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Khu CNC Hòa Lạc, Thạch Thất, Hà Nội",
                            Name = "Sân cầu lông Phú Cát",
                            OwnerId = 2
                        },
                        new
                        {
                            Id = 2,
                            Address = "Thôn 3, Thạch Hòa, Thạch Thất, Hà Nội",
                            Name = "Sân cầu lông Hòa Lạc",
                            OwnerId = 2
                        });
                });

            modelBuilder.Entity("BadmintonBookingAPI.Models.SubCourt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.ToTable("SubCourts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourtId = 1,
                            Name = "Sân 1"
                        },
                        new
                        {
                            Id = 2,
                            CourtId = 1,
                            Name = "Sân 2"
                        },
                        new
                        {
                            Id = 3,
                            CourtId = 1,
                            Name = "Sân 3"
                        },
                        new
                        {
                            Id = 4,
                            CourtId = 2,
                            Name = "Sân 1"
                        },
                        new
                        {
                            Id = 5,
                            CourtId = 2,
                            Name = "Sân 2"
                        });
                });

            modelBuilder.Entity("BadmintonBookingAPI.Models.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("bit");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SubCourtId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubCourtId");

                    b.ToTable("TimeSlots");
                });

            modelBuilder.Entity("BadmintonBookingAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            Password = "123456",
                            Phone = "0900000000",
                            Role = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Nguyễn Văn A",
                            Password = "123456",
                            Phone = "0901234567",
                            Role = "owner"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Trần Thị B",
                            Password = "123456",
                            Phone = "0907654321",
                            Role = "player"
                        });
                });

            modelBuilder.Entity("BadmintonBookingAPI.Models.Booking", b =>
                {
                    b.HasOne("BadmintonBookingAPI.Models.TimeSlot", "TimeSlot")
                        .WithMany("Bookings")
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BadmintonBookingAPI.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TimeSlot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BadmintonBookingAPI.Models.Court", b =>
                {
                    b.HasOne("BadmintonBookingAPI.Models.User", "Owner")
                        .WithMany("Courts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BadmintonBookingAPI.Models.SubCourt", b =>
                {
                    b.HasOne("BadmintonBookingAPI.Models.Court", "Court")
                        .WithMany("SubCourts")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");
                });

            modelBuilder.Entity("BadmintonBookingAPI.Models.TimeSlot", b =>
                {
                    b.HasOne("BadmintonBookingAPI.Models.SubCourt", "SubCourt")
                        .WithMany("TimeSlots")
                        .HasForeignKey("SubCourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCourt");
                });

            modelBuilder.Entity("BadmintonBookingAPI.Models.Court", b =>
                {
                    b.Navigation("SubCourts");
                });

            modelBuilder.Entity("BadmintonBookingAPI.Models.SubCourt", b =>
                {
                    b.Navigation("TimeSlots");
                });

            modelBuilder.Entity("BadmintonBookingAPI.Models.TimeSlot", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BadmintonBookingAPI.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Courts");
                });
#pragma warning restore 612, 618
        }
    }
}
